In [ ]:
# coding: UTF-8
import numpy as np
import h5py
import csv


#im = 64
#jm = 64
#km = 64
im = 128
jm = 128
km = 128
#im = 512
#jm = 512
#km = 512
#num = 1
#num = 3
#num = 7
#num = 17
num = 18
nstep = 20
#itime = 1
#ftime = 104
itime = 80
ftime = 102
timejump=4
#dir = '/glv0/maedarn/clst-form-HIcol/DTF/DTFm10-disp0-2-nolog/'
#dir = '/glv0/maedarn/clst-form-HIcol/cnv100-wb-wg-sm/'
#dir = '/glv0/maedarn/clst-form-HIcol/cnv100-wsb-wg-sm-200pc/'
#dir = '/glv0/maedarn/clst-form-HIcol/cnv100-wb-wg-sm/Clmpanly/'
#dir = '/glv0/maedarn/dbug/debuggausssidelwb/'
#dir = '/glv0/maedarn/clst-form-HIcol/cnv100-wb-wg-sm-optthick/'
dir = '/Users/maeda/Desktop/Dropbox/analysis/test-feedback/collide-cloud7/'

for j in range(itime,ftime +1,timejump): #最後は含まない
    #f90 = open(dir+'All/All'+"%03.f"%(i)+'.DAT', 'rb')
    f90 = open(dir+'AllHDF/AllHDF'+"%03.f"%(j)+'.DAT', 'rb')
    #f90 = open(dir+'dbug-ok/Alldphi'+"%03.f"%(i)+'.DAT', 'rb')
    #f90 = open(dir+'All/All'+"%03.f"%(i)+'.DAT', 'rb')
    #f90 = open(dir+'tag/tag'+"%03.f"%(i)+'003.DAT', 'rb')
    #f90 = open(dir+'All/All'+"%03.f"%(i)+'.DAT', 'rb')
    #f90 = open(dir+'Clmpanly/CN098001.DAT', 'rb')
    #f90 = open(dir+'AllD.DAT', 'rb')
    ary = np.fromfile(f90, np.float32,count=im*jm*km*num) #count=im*jm*dim*nstep
    #ary = np.fromfile(f90, np.int32,count=im*jm*km*num)
    #print(ary)
    uvhpy = ary.reshape(num,im,jm,km, order='F')
    #print(uvhpy)
    
    #slice2=uvhpy[1,:,:,:]
    slice1=uvhpy[0,:,:,:]
    slice2=uvhpy[1,:,:,:]
    slice3=uvhpy[2,:,:,:]
    slice4=uvhpy[3,:,:,:]
    slice5=uvhpy[4,:,:,:]
    slice6=uvhpy[5,:,:,:]
    slice7=uvhpy[6,:,:,:]
    slice8=uvhpy[7,:,:,:]
    slice9=uvhpy[8,:,:,:]
    slice10=uvhpy[9,:,:,:]
    slice11=uvhpy[10,:,:,:]
    slice12=uvhpy[11,:,:,:]
    slice13=uvhpy[12,:,:,:]
    slice14=uvhpy[13,:,:,:]
    slice15=uvhpy[14,:,:,:]
    slice16=uvhpy[15,:,:,:]
    slice17=uvhpy[16,:,:,:]
    slice18=uvhpy[17,:,:,:]

    #shock trace
    sliceshockrho = np.where(slice1 >= 10.0, 1, 0)
    sliceshockvx = np.where(abs(slice2) <= 10.0, 1, 0)
    sliceshock = sliceshockrho + sliceshockvx
    sliceshock = np.where(sliceshock >= 1, 1, 0)
    
    #density trace
    slicerho10000 = np.where(slice1 >= 10000.0, 1, 0)
    slicerho1000 = np.where(slice1 >= 1000.0, 1, 0)
    slicerho100 = np.where(slice1 >= 100.0, 1, 0)
    


    slice1shock=sliceshock*slice1
    slice1rho10000=sliceshock*slicerho10000
    slice1rho1000=sliceshock*slicerho1000
    slice1rho100=sliceshock*slicerho100
    sliceshocksf=sliceshock*slice1
    
    slice1rho10000xp=sliceshock*slicerho10000
    slice1rho1000xp=sliceshock*slicerho1000
    slice1rho100xp=sliceshock*slicerho100
    slice1rho10000xm=sliceshock*slicerho10000
    slice1rho1000xm=sliceshock*slicerho1000
    slice1rho100xm=sliceshock*slicerho100
    slice1rho10000yp=sliceshock*slicerho10000
    slice1rho1000yp=sliceshock*slicerho1000
    slice1rho100yp=sliceshock*slicerho100
    slice1rho10000ym=sliceshock*slicerho10000
    slice1rho1000ym=sliceshock*slicerho1000
    slice1rho100ym=sliceshock*slicerho100
    slice1rho10000zp=sliceshock*slicerho10000
    slice1rho1000zp=sliceshock*slicerho1000
    slice1rho100zp=sliceshock*slicerho100
    slice1rho10000zm=sliceshock*slicerho10000
    slice1rho1000zm=sliceshock*slicerho1000
    slice1rho100zm=sliceshock*slicerho100
    
    u1=slice1rho100zm
    
    
    
    for i in range(0,im):
        sliceshocksf[i,:,:]=sliceshock[i+1-(im)*int(1/(im-i)),:,:]+sliceshock[i-1-(im)*int(1/(im+i)),:,:]
        
        
        slice1rho10000xp[i,:,:] =slice1rho10000[i+1-(im)*int(1/(im-i)),:,:]
        slice1rho10000xm[i,:,:]=slice1rho10000[i-1+(im)*int(im/(im+i)),:,:]
        slice1rho10000yp[:,i,:] =slice1rho10000[:,i+1-(jm)*int(1/(jm-i)),:]
        slice1rho10000ym[:,i,:]=slice1rho10000[:,i-1+(jm)*int(jm/(jm+i)),:]
        slice1rho10000zp[:,:,i] =slice1rho10000[:,:,i+1-(km)*int(1/(km-i))]
        slice1rho10000zm[:,:,i]=slice1rho10000[:,:,i-1+(km)*int(km/(km+i))]
        
        
        slice1rho1000xp[i,:,:] =slice1rho1000[i+1-(im)*int(1/(im-i)),:,:]
        slice1rho1000xm[i,:,:]=slice1rho1000[i-1+(im)*int(im/(im+i)),:,:]
        slice1rho1000yp[:,i,:] =slice1rho1000[:,i+1-(jm)*int(1/(jm-i)),:]
        slice1rho1000ym[:,i,:]=slice1rho1000[:,i-1+(jm)*int(jm/(jm+i)),:]
        slice1rho1000zp[:,:,i] =slice1rho1000[:,:,i+1-(km)*int(1/(km-i))]
        slice1rho1000zm[:,:,i]=slice1rho1000[:,:,i-1+(km)*int(km/(km+i))]
        
        
        slice1rho100xp[i,:,:] =slice1rho100[i+1-(im)*int(1/(im-i)),:,:]
        slice1rho100xm[i,:,:]=slice1rho100[i-1+(im)*int(im/(im+i)),:,:]
        slice1rho100yp[:,i,:] =slice1rho100[:,i+1-(jm)*int(1/(jm-i)),:]
        slice1rho100ym[:,i,:]=slice1rho100[:,i-1+(jm)*int(jm/(jm+i)),:]
        slice1rho100zp[:,:,i] =slice1rho100[:,:,i+1-(km)*int(1/(km-i))]
        slice1rho100zm[:,:,i]=slice1rho100[:,:,i-1+(km)*int(km/(km+i))]
        
        

    sliceshocksf= np.where(sliceshocksf == 1, 1, 0)
    
    slice1rho10000sf=slice1rho10000xp +slice1rho10000xm+slice1rho10000yp +slice1rho10000ym+slice1rho10000zp +slice1rho10000zm
    slice1rho10000sf=np.where(slice1rho10000sf <= 1, 1, 0)
    slice1rho10000sf=slice1rho10000sf*slice1rho10000
    
    slice1rho1000sf=slice1rho1000xp +slice1rho1000xm+slice1rho1000yp +slice1rho1000ym+slice1rho1000zp +slice1rho1000zm
    slice1rho1000sf=np.where(slice1rho1000sf <= 1, 1, 0)
    slice1rho1000sf=slice1rho1000sf*slice1rho1000
    
    slice1rho100sf=slice1rho100xp +slice1rho100xm+slice1rho100yp +slice1rho100ym+slice1rho100zp +slice1rho100zm
    slice1rho100sf=np.where(slice1rho100sf <= 1, 1, 0)
    slice1rho100sf=slice1rho100sf*slice1rho100
    
    
    #a[a < 5].mean()
    #s1=slice1shock[slice1shock>0].mean()
    #s2=slice2shock[slice2shock!=0].std()
   
    
    #print(np.mean(a, axis=0))
    #print(np.mean(a, axis=1))
    
    #smean = [stime,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16,s17,s18]
    #smean = [stime,s1,s5]
    
    
    #with open(dir+'AllHDF/psrmeantimeallval.csv', mode='a') as file:
    #f.write(smean)
      #  writer = csv.writer(file, lineterminator='\n')
       # writer.writerow(smean)
    
    

#print("2次元配列で、15以上の場合は1、それ以外は0に配列の要素を置換")
#upNpArray = np.where(npArray >= 15, 1, 0)
#print(upNpArray)

#print("2次元配列で、15以上の場合は元の配列のままとし、それ以外は0に配列の要素を置換")
#upNpArray = np.where(npArray >= 15, npArray, 0)
#print(upNpArray)
    with h5py.File(dir+'AllHDF/SFHDF'+"%03.f"%(j)+'.h5', 'w') as f:
    #  f.create_group('PHI')
    #  f['PHI'].create_dataset('PHI', data=slice1)
    
        f.create_group('RHO')
        f['RHO'].create_dataset('RHO', data=slice1)
        
        f.create_group('SF')
        #f['SF'].create_dataset('SK1', data=u1)
        #f['SF'].create_dataset('SK2', data=slice1rho100zm)
        #f['SF'].create_dataset('SK2', data=sngl(slice1rho100zm))
        f['SF'].create_dataset('SK', data=sliceshocksf)
        f['SF'].create_dataset('10000', data=slice1rho10000sf)
        f['SF'].create_dataset('1000', data=slice1rho1000sf)
        f['SF'].create_dataset('100', data=slice1rho100sf)
        



In [4]:
# coding: UTF-8
import numpy as np
import h5py
import csv
from scipy import special


#im = 64
#jm = 64
#km = 64
im = 128
jm = 128
km = 128
#im = 512
#jm = 512
#km = 512
#num = 1
#num = 3
#num = 7
#num = 17
num = 18
nstep = 20
#itime = 1
#ftime = 104
itime = 90
ftime =90
timejump=1
dx1=100.0/512.0
Ms=0.024

b=0.5 
ep=1.0
pt=1.0
phx=1.12
#ms=1.0
yc=0.1

#dir = '/Users/maeda/Desktop/Dropbox/analysis/samplecnvD/'
dir = '/Users/maeda/Desktop/Dropbox/analysis/samplecnvA/Phi/Maeda2021/'


for j in range(itime,ftime +1,timejump): #最後は含まない
    #f90 = open(dir+'All/All'+"%03.f"%(i)+'.DAT', 'rb')
    #f90 = open(dir+'HCLALL'+"%03.f"%(j)+'.DAT', 'rb')
    f90 = open(dir+'AllHDF'+"%03.f"%(j)+'.DAT', 'rb')
    ary = np.fromfile(f90, np.float32,count=im*jm*km*num) #count=im*jm*dim*nstep
    #ary = np.fromfile(f90, np.int32,count=im*jm*km*num)
    #print(ary)
    uvhpy = ary.reshape(num,im,jm,km, order='F')
    #print(uvhpy)
    
    #slice2=uvhpy[1,:,:,:]
    slice1=uvhpy[0,:,:,:]
    slice2=uvhpy[1,:,:,:]
    slice3=uvhpy[2,:,:,:]
    slice4=uvhpy[3,:,:,:]
    slice5=uvhpy[4,:,:,:]
    slice6=uvhpy[5,:,:,:]
    slice7=uvhpy[6,:,:,:]
    slice8=uvhpy[7,:,:,:]
    slice9=uvhpy[8,:,:,:]
    slice10=uvhpy[9,:,:,:]
    slice11=uvhpy[10,:,:,:]
    slice12=uvhpy[11,:,:,:]
    slice13=uvhpy[12,:,:,:]
    slice14=uvhpy[13,:,:,:]
    slice15=uvhpy[14,:,:,:]
    slice16=uvhpy[15,:,:,:]
    slice17=uvhpy[16,:,:,:]
    slice18=uvhpy[17,:,:,:]
    
    Gphi = np.zeros((im,jm,km), dtype=np.float)
    for ii in range(0+1, im-1 ):
        for jj in range(0+1, jm-1 ):
            for kk in range(0+1, km-1 ):
                Gphi[ii,jj,kk]=-slice17[ii,jj,kk]+1.0/26.0*(slice17[ii+1,jj+1,kk+1]+slice17[ii+1,jj+1,kk]+slice17[ii+1,jj+1,kk-1]+slice17[ii+1,jj,kk+1]+slice17[ii+1,jj,kk]+slice17[ii+1,jj,kk-1]+slice17[ii+1,jj-1,kk+1]+slice17[ii+1,jj-1,kk]+slice17[ii+1,jj-1,kk-1]+slice17[ii,jj+1,kk+1]+slice17[ii,jj+1,kk]+slice17[ii,jj+1,kk-1]+slice17[ii,jj,kk+1]+slice17[ii,jj,kk-1]+slice17[ii,jj-1,kk+1]+slice17[ii,jj-1,kk]+slice17[ii,jj-1,kk-1]+slice17[ii-1,jj+1,kk+1]+slice17[ii-1,jj+1,kk]+slice17[ii-1,jj+1,kk-1]+slice17[ii-1,jj,kk+1]+slice17[ii-1,jj,kk]+slice17[ii-1,jj,kk-1]+slice17[ii-1,jj-1,kk+1]+slice17[ii-1,jj-1,kk]+slice17[ii-1,jj-1,kk-1])

    MtoF=np.sqrt(0.000111142*3.1415926535)*slice1*dx1/np.sqrt(slice6**2.0+slice7**2.0+slice8**2.0)
    SFRhoth = np.where(slice11 > 100.0, 1.0, 0.0)
    SFTth = np.where(slice18 < 100.0/1000.0, 1.0, 0.0)
    SF=SFTth*SFRhoth 
    MJ=np.where(slice1*dx1*dx1*dx1* Ms > 2*(slice1/1.27)**(-0.5)*(slice18/0.01)**(3.0/2.0), 1.0, 0.0)
    MJmg=np.where(slice1*dx1*dx1*dx1* Ms > 2*(slice1/1.27)**(-0.5)*(slice18/0.01)**(3.0/2.0) * ((1.0+(slice5*2.0/(slice6**2.0+slice7**2.0+slice8**2.0))**(-1.0)))**(3.0/2.0), 1.0, 0.0)
    #bt = slice5*2.0/(slice6**2.0+slice7**2.0+slice8**2.0)
    bt = 100.0
    ms=0.2*np.sqrt(slice18/0.01)
    ac=5.0/3.0*(slice2*slice2+slice3*slice3+slice4*slice4)*dx1/0.0001111/slice1/dx1/dx1/dx1*0.1
    s=np.sqrt(np.log(1.0+b*b*ms*ms*bt/(bt+1.0)))
    sc=np.log(3.1415*3.1415/5.0/yc/yc*ac/ms/ms*(1.0+1.0/bt)**(1.0))
    SFR=ep*0.5/pt*(1+special.erf((s*s-sc)/((2.0*s*s)**0.50)))*np.exp(3.0*s*s/8.0)
    SFE=1.0/(1.0+1.0/SFR)
    LSFE=0.02*np.sqrt(slice1/(4.04*1000.0))*dx1/50.0
    
    StFmRg=slice6**2.0+slice7**2.0+slice8**2.0+slice5-Gphi*slice1
    
    
    
    print(SF)

    
    with h5py.File(dir+'NNNSFEPhitoFHDF'+"%03.f"%(j)+'.h5', 'w') as f:
    #  f.create_group('PHI')
    #  f['PHI'].create_dataset('PHI', data=slice1)
    
        f.create_group('RHO')
        f['RHO'].create_dataset('RHO', data=slice1)
        
        f.create_group('T')
        f['T'].create_dataset('T', data=slice18)
        
        f.create_group('MtoF')
        f['MtoF'].create_dataset('MtoF', data=MtoF)
        
        f.create_group('SF')
        f['SF'].create_dataset('SF', data=SF)
        
        f.create_group('MJ')
        f['MJ'].create_dataset('MJ', data=MJ)
        
        f.create_group('MJmg')
        f['MJmg'].create_dataset('MJmg', data=MJmg)
        
        f.create_group('Beta')
        f['Beta'].create_dataset('Beta', data=bt)
        
        f.create_group('SFE')
        f['SFE'].create_dataset('SFE', data=SFE)
        
        f.create_group('LSFE')
        f['LSFE'].create_dataset('LSFE', data=LSFE)
        
        f.create_group('Phi')
        f['Phi'].create_dataset('Phi', data=slice17)
        
        f.create_group('StFmRg')
        f['StFmRg'].create_dataset('StFmRg', data=StFmRg)
        

        
    


/Users/maeda/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/ipykernel_launcher.py:91: RuntimeWarning: divide by zero encountered in true_divide


[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [67]:
#Gphi=slice17
#Gphi=0.0

Gphi = np.zeros((im,jm,km), dtype=np.float)
#print(Gphi)

for ii in range(0+1, im-1 ):
    for jj in range(0+1, jm-1 ):
        for kk in range(0+1, km-1 ):
            Gphi[ii,jj,kk]=-slice17[ii,jj,kk]+1.0/26.0*(slice17[ii+1,jj+1,kk+1]+slice17[ii+1,jj+1,kk]+slice17[ii+1,jj+1,kk-1]+slice17[ii+1,jj,kk+1]+slice17[ii+1,jj,kk]+slice17[ii+1,jj,kk-1]+slice17[ii+1,jj-1,kk+1]+slice17[ii+1,jj-1,kk]+slice17[ii+1,jj-1,kk-1]+slice17[ii,jj+1,kk+1]+slice17[ii,jj+1,kk]+slice17[ii,jj+1,kk-1]+slice17[ii,jj,kk+1]+slice17[ii,jj,kk-1]+slice17[ii,jj-1,kk+1]+slice17[ii,jj-1,kk]+slice17[ii,jj-1,kk-1]+slice17[ii-1,jj+1,kk+1]+slice17[ii-1,jj+1,kk]+slice17[ii-1,jj+1,kk-1]+slice17[ii-1,jj,kk+1]+slice17[ii-1,jj,kk]+slice17[ii-1,jj,kk-1]+slice17[ii-1,jj-1,kk+1]+slice17[ii-1,jj-1,kk]+slice17[ii-1,jj-1,kk-1])

            
print(Gphi)

[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
    0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
    0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
    0.00000000e+00  0.00000000e+00]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
    0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
    0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
    0.00000000e+00  0.00000000e+00]]

 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
    0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  8.06526067e+01  7.35783785e+01 ...  7.35714675e+01
    7.35730544e+01  0.00000000e+00]
  [ 0.00000000e+00 -1.41509581e+01 -2.12266587e+01 ... -2.12248324e+01
   -2.12252526e+01  0.00000000e+00]
  ...
  [ 0.00000000e+00  1.6

In [57]:
Gphi = np.zeros((im,jm,km), dtype=np.float)
print(Gphi)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [1]:

# coding: UTF-8
import numpy as np
import h5py
import csv
from scipy import special


#im = 64
#jm = 64
#km = 64
im = 128
jm = 128
km = 128
#im = 512
#jm = 512
#km = 512
#num = 1
#num = 3
#num = 7
#num = 17
num = 18
nstep = 20
#itime = 1
#ftime = 104
itime = 98
ftime =98
timejump=1
dx1=100.0/512.0
Ms=0.024

b=0.5 
ep=1.0
pt=1.0
phx=1.12
#ms=1.0
yc=0.1

#dir = '/Users/maeda/Desktop/Dropbox/analysis/samplecnvD/'
dir = '/Users/maeda/Desktop/Dropbox/analysis/samplecnvA/Phi/Maeda2021/'
f90 = open(dir+'AllHDF'+"%03.f"%(j)+'.DAT', 'rb')
ary = np.fromfile(f90, np.float32,count=im*jm*km*num) #count=im*jm*dim*nstep
uvhpy = ary.reshape(num,im,jm,km, order='F')

slice1=uvhpy[0,:,:,:]
slice2=uvhpy[1,:,:,:]
slice3=uvhpy[2,:,:,:]
slice4=uvhpy[3,:,:,:]
slice5=uvhpy[4,:,:,:]
slice6=uvhpy[5,:,:,:]
slice7=uvhpy[6,:,:,:]
slice8=uvhpy[7,:,:,:]
slice9=uvhpy[8,:,:,:]
slice10=uvhpy[9,:,:,:]
slice11=uvhpy[10,:,:,:]
slice12=uvhpy[11,:,:,:]
slice13=uvhpy[12,:,:,:]
slice14=uvhpy[13,:,:,:]
slice15=uvhpy[14,:,:,:]
slice16=uvhpy[15,:,:,:]
slice17=uvhpy[16,:,:,:]
slice18=uvhpy[17,:,:,:]

print('fin')

NameError: name 'j' is not defined

In [11]:
Gphi = np.zeros((im,jm,km), dtype=np.float)
vcx = np.zeros((im,jm,km), dtype=np.float)
vcy = np.zeros((im,jm,km), dtype=np.float)
vcz = np.zeros((im,jm,km), dtype=np.float)


for ii in range(0+1, im-1 ):
    for jj in range(0+1, jm-1 ):
        for kk in range(0+1, km-1 ):
            Gphi[ii,jj,kk]=-slice17[ii,jj,kk]+1.0/26.0*(slice17[ii+1,jj+1,kk+1]+slice17[ii+1,jj+1,kk]+slice17[ii+1,jj+1,kk-1]+slice17[ii+1,jj,kk+1]+slice17[ii+1,jj,kk]+slice17[ii+1,jj,kk-1]+slice17[ii+1,jj-1,kk+1]+slice17[ii+1,jj-1,kk]+slice17[ii+1,jj-1,kk-1]+slice17[ii,jj+1,kk+1]+slice17[ii,jj+1,kk]+slice17[ii,jj+1,kk-1]+slice17[ii,jj,kk+1]+slice17[ii,jj,kk-1]+slice17[ii,jj-1,kk+1]+slice17[ii,jj-1,kk]+slice17[ii,jj-1,kk-1]+slice17[ii-1,jj+1,kk+1]+slice17[ii-1,jj+1,kk]+slice17[ii-1,jj+1,kk-1]+slice17[ii-1,jj,kk+1]+slice17[ii-1,jj,kk]+slice17[ii-1,jj,kk-1]+slice17[ii-1,jj-1,kk+1]+slice17[ii-1,jj-1,kk]+slice17[ii-1,jj-1,kk-1])

MtoF=np.sqrt(0.000111142*3.1415926535)*slice1*dx1/np.sqrt(slice6**2.0+slice7**2.0+slice8**2.0)
SFRhoth = np.where(slice11 > 100.0, 1.0, 0.0)
SFTth = np.where(slice18 < 100.0/1000.0, 1.0, 0.0)
SF=SFTth*SFRhoth 
MJ=np.where(slice1*dx1*dx1*dx1* Ms > 2*(slice1/1.27)**(-0.5)*(slice18/0.01)**(3.0/2.0), 1.0, 0.0)
MJmg=np.where(slice1*dx1*dx1*dx1* Ms > 2*(slice1/1.27)**(-0.5)*(slice18/0.01)**(3.0/2.0) * ((1.0+(slice5*2.0/(slice6**2.0+slice7**2.0+slice8**2.0))**(-1.0)))**(3.0/2.0), 1.0, 0.0)
bt = 100.0
ms=0.2*np.sqrt(slice18/0.01)
ac=5.0/3.0*(slice2*slice2+slice3*slice3+slice4*slice4)*dx1/0.0001111/slice1/dx1/dx1/dx1*0.1
s=np.sqrt(np.log(1.0+b*b*ms*ms*bt/(bt+1.0)))
sc=np.log(3.1415*3.1415/5.0/yc/yc*ac/ms/ms*(1.0+1.0/bt)**(1.0))
SFR=ep*0.5/pt*(1+special.erf((s*s-sc)/((2.0*s*s)**0.50)))*np.exp(3.0*s*s/8.0)
SFE=1.0/(1.0+1.0/SFR)
LSFE=0.02*np.sqrt(slice1/(4.04*1000.0))*dx1/50.0
    
StFmRg=(slice6**2.0+slice7**2.0+slice8**2.0)*0.5+slice1*3.0/5.0-Gphi*slice1#+(slice2**2.0+slice3**2.0+slice4**2.0)*0.5*slice1
    
    
    
#print(SF)

    
with h5py.File(dir+'New6SFEPhitoFHDF'+"%03.f"%(j)+'.h5', 'w') as f:
    
    f.create_group('RHO')
    f['RHO'].create_dataset('RHO', data=slice1)
        
    f.create_group('T')
    f['T'].create_dataset('T', data=slice18)
        
    f.create_group('MtoF')
    f['MtoF'].create_dataset('MtoF', data=MtoF)
        
    f.create_group('SF')
    f['SF'].create_dataset('SF', data=SF)
        
    f.create_group('MJ')
    f['MJ'].create_dataset('MJ', data=MJ)
        
    f.create_group('MJmg')
    f['MJmg'].create_dataset('MJmg', data=MJmg)
        
    f.create_group('Beta')
    f['Beta'].create_dataset('Beta', data=bt)
        
    f.create_group('SFE')
    f['SFE'].create_dataset('SFE', data=SFE)
        
    f.create_group('LSFE')
    f['LSFE'].create_dataset('LSFE', data=LSFE)
        
    f.create_group('Phi')
    f['Phi'].create_dataset('Phi', data=slice17)
        
    f.create_group('StFmRg')
    f['StFmRg'].create_dataset('StFmRg', data=StFmRg)
        

        
print('fini')    


/Users/maeda/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/ipykernel_launcher.py:24: RuntimeWarning: divide by zero encountered in true_divide


fini
